// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/broker.proto

package brokerrpc

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quotes_EncodingType int32

const (
	Quotes_KAMBALA Quotes_EncodingType = 0
)

// Enum value maps for Quotes_EncodingType.
var (
	Quotes_EncodingType_name = map[int32]string{
		0: "KAMBALA",
	}
	Quotes_EncodingType_value = map[string]int32{
		"KAMBALA": 0,
	}
)

func (x Quotes_EncodingType) Enum() *Quotes_EncodingType {
	p := new(Quotes_EncodingType)
	*p = x
	return p
}

func (x Quotes_EncodingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quotes_EncodingType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_broker_proto_enumTypes[0].Descriptor()
}

func (Quotes_EncodingType) Type() protoreflect.EnumType {
	return &file_api_broker_proto_enumTypes[0]
}

func (x Quotes_EncodingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quotes_EncodingType.Descriptor instead.
func (Quotes_EncodingType) EnumDescriptor() ([]byte, []int) {
	return file_api_broker_proto_rawDescGZIP(), []int{1, 0}
}

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subscribe to updates for these instruments.
	Subscribe []int64 `protobuf:"varint,1,rep,packed,name=subscribe,proto3" json:"subscribe,omitempty"`
	// Unsubscribe from updates for these instruments.
	Unsubscribe []int64 `protobuf:"varint,2,rep,packed,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_broker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetSubscribe() []int64 {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

func (x *StreamRequest) GetUnsubscribe() []int64 {
	if x != nil {
		return x.Unsubscribe
	}
	return nil
}

type Quotes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encoding Quotes_EncodingType `protobuf:"varint,1,opt,name=encoding,proto3,enum=tickerfeed.Quotes_EncodingType" json:"encoding,omitempty"`
	Quotes   []*Quote            `protobuf:"bytes,2,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *Quotes) Reset() {
	*x = Quotes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_broker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quotes) ProtoMessage() {}

func (x *Quotes) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quotes.ProtoReflect.Descriptor instead.
func (*Quotes) Descriptor() ([]byte, []int) {
	return file_api_broker_proto_rawDescGZIP(), []int{1}
}

func (x *Quotes) GetEncoding() Quotes_EncodingType {
	if x != nil {
		return x.Encoding
	}
	return Quotes_KAMBALA
}

func (x *Quotes) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type Quote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstrumentId       int64                  `protobuf:"varint,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	QuoteData          []byte                 `protobuf:"bytes,3,opt,name=quote_data,json=quoteData,proto3" json:"quote_data,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DerivedFuturePrice int64                  `protobuf:"varint,5,opt,name=derived_future_price,json=derivedFuturePrice,proto3" json:"derived_future_price,omitempty"`
}

func (x *Quote) Reset() {
	*x = Quote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_broker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_api_broker_proto_rawDescGZIP(), []int{2}
}

func (x *Quote) GetInstrumentId() int64 {
	if x != nil {
		return x.InstrumentId
	}
	return 0
}

func (x *Quote) GetQuoteData() []byte {
	if x != nil {
		return x.QuoteData
	}
	return nil
}

func (x *Quote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Quote) GetDerivedFuturePrice() int64 {
	if x != nil {
		return x.DerivedFuturePrice
	}
	return 0
}

var File_api_broker_proto protoreflect.FileDescriptor

var file_api_broker_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x65, 0x65, 0x64, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x22, 0x8d, 0x01, 0x0a, 0x06, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x08, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x73, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x06, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x73, 0x22, 0x1b, 0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4b, 0x41, 0x4d, 0x42, 0x41, 0x4c, 0x41, 0x10, 0x00,
	0x22, 0xb7, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x72, 0x69,
	0x76, 0x65, 0x64, 0x5f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x64, 0x46,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x51, 0x0a, 0x0a, 0x46, 0x65,
	0x65, 0x64, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a,
	0x0d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_broker_proto_rawDescOnce sync.Once
	file_api_broker_proto_rawDescData = file_api_broker_proto_rawDesc
)

func file_api_broker_proto_rawDescGZIP() []byte {
	file_api_broker_proto_rawDescOnce.Do(func() {
		file_api_broker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_broker_proto_rawDescData)
	})
	return file_api_broker_proto_rawDescData
}

var file_api_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_broker_proto_goTypes = []interface{}{
	(Quotes_EncodingType)(0),      // 0: tickerfeed.Quotes.EncodingType
	(*StreamRequest)(nil),         // 1: tickerfeed.StreamRequest
	(*Quotes)(nil),                // 2: tickerfeed.Quotes
	(*Quote)(nil),                 // 3: tickerfeed.Quote
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_broker_proto_depIdxs = []int32{
	0, // 0: tickerfeed.Quotes.encoding:type_name -> tickerfeed.Quotes.EncodingType
	3, // 1: tickerfeed.Quotes.quotes:type_name -> tickerfeed.Quote
	4, // 2: tickerfeed.Quote.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: tickerfeed.FeedBroker.StreamQuotes:input_type -> tickerfeed.StreamRequest
	2, // 4: tickerfeed.FeedBroker.StreamQuotes:output_type -> tickerfeed.Quotes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_broker_proto_init() }
func file_api_broker_proto_init() {
	if File_api_broker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_broker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_broker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quotes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_broker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_broker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_broker_proto_goTypes,
		DependencyIndexes: file_api_broker_proto_depIdxs,
		EnumInfos:         file_api_broker_proto_enumTypes,
		MessageInfos:      file_api_broker_proto_msgTypes,
	}.Build()
	File_api_broker_proto = out.File
	file_api_broker_proto_rawDesc = nil
	file_api_broker_proto_goTypes = nil
	file_api_broker_proto_depIdxs = nil
}
